config/routes.rb
Rails.application.routes.draw do
  get 'users/intro' => 'users#intro'
  get 'users/trash' => 'users#trash'
  get 'users/bank_instructions' => 'users#bank_instructions'
  get :send_payment_confirmation, to: 'users#send_payment_confirmation', as: :send_payment_confirmation
  get :restore_data, to: 'transactions#restore_data', as: :restore_data

  devise_scope :user do
    root to: 'users#intro'
  end

  devise_for :users, controllers: { registrations: "registrations" }

  resources :users, only: [:index, :show]
  resources :transactions, only: [:edit, :update]

  resources :users do
    resources :transactions, only: [:create, :destroy]
    resources :tickets, only: [:create, :destroy]
  end

  resources :transactions do
    resources :tickets, only: [:update]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :payment, foreign_key: :transaction_id, class_name: :Transaction

  validates :number, uniqueness: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  require 'csv'
  acts_as_paranoid

  belongs_to :user
  has_many :tickets

  validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/, :on => [:create, :update] }
  validates :full_name, presence: true
  validates :quantity, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 100 }
  validates :price, numericality: { greater_than_or_equal_to: 0 }

  def self.to_csv
    attributes = %w{full_name email ministry quantity price payment_check deposit_check date_deposited}
    CSV.generate(headers: true) do |csv|
      csv << attributes
      all.each do |transaction|
        csv << attributes.map{ |attr| transaction.send(attr) }
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
         :recoverable, :rememberable, :registerable, :trackable, :validatable, :confirmable

  has_many :transactions
  has_many :tickets, through: :transactions

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    user_session_url
  end

  def after_inactive_sign_up_path_for(resource)
    user_session_url
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_ticket
    @ticket = Ticket.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ticket_params
    params.require(:ticket).permit(:number, :transaction_id)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :load_transaction, only: [:edit, :update, :destroy]

  def create
    @transaction = Transaction.new(transaction_params)
    @user = @transaction.user
    @transactions = @user.transactions
    calculate_price
    respond_to do |format|
      if @transaction.save
        @transaction.quantity.times { Ticket.create(number: rand(100000..999999), transaction_id: @transaction.id) }
        format.html { redirect_to user_url(@user), notice:'Transaction added & ticket #s generated' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render 'users/show' }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @user = current_user
  end

  def update
    respond_to do |format|
      if @transaction.update_attributes(transaction_params)
        update_ticket_numbers
        calculate_price
        format.html { redirect_to user_url(current_user), notice: 'Transaction info updated' }
        format.json { render json: current_user, status: :created, location: current_user }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = @transaction.user
    respond_to do |format|
      UserMailer.delete_notice(@transaction).deliver_later
      @transaction.destroy
      format.html { redirect_to user_url(@user), notice:'Transaction moved to trash & notification email sent' }
      format.json { render json: @user, status: :created, location: @user }
    end
  end

  def restore_data
    @transaction = Transaction.only_deleted.find(params[:id])
    @transaction.recover
    @transaction.update_attributes(sent_confirmation: 0)
    redirect_to user_url(current_user), notice: 'Transaction data restored'
  end

  private

  def load_transaction
    @transaction = Transaction.find(params[:id])
  end

  def transaction_params
    params.require(:transaction).permit(:full_name, :email, :ministry, :price, :quantity,
    :payment_check, :user_id, :ticket_numbers, :deposit_check, :date_deposited, :sent_confirmation)
  end

  def calculate_price
    if @transaction.quantity != nil && @transaction.quantity % 2 != 0
      n = @transaction.quantity * 2.50
      @transaction.update_attributes(price: n + 0.5)
    elsif @transaction.quantity != nil && @transaction.quantity % 2 == 0
      n = @transaction.quantity * 2.50
      @transaction.update_attributes(price: n)
    end
  end

  def update_ticket_numbers
    if @transaction.tickets.count < @transaction.quantity
      i = @transaction.quantity - @transaction.tickets.count
      i.times { Ticket.create(number: rand(100000..999999), transaction_id: @transaction.id) }
    elsif @transaction.tickets.count > @transaction.quantity
      i = @transaction.tickets.count - @transaction.quantity
      i.times { @transaction.tickets.last.destroy }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :verify_admin, only: [:index]
  before_action :load_user, only: [:show, :send_payment_confirmation]
  before_action :load_admin, only: [:index, :trash]

  def intro
  end

  def index
    @users = User.all
    @transactions = Transaction.where(payment_check: 1)
  end

  def show
    @transaction = Transaction.new
    @transactions = Transaction.where(user_id: @user)
    @csv_transactions = Transaction.all
    @tickets = @user.tickets
    respond_to do |format|
      format.html
      format.csv { send_data @csv_transactions.to_csv, filename: "OPS-Raffle/#{Date.today}.csv" }
    end
  end

  def trash
    @transactions = Transaction.only_deleted.where(user_id: @user.id)
  end

  def bank_instructions
  end

  def send_payment_confirmation
    @transaction = Transaction.find(params[:id])
    respond_to do |format|
      @transaction.update_attributes(sent_confirmation: 1)
      UserMailer.payment_confirmation(@transaction).deliver_later
      format.html { redirect_to user_url(@user), notice:'Ticket confirmation email sent' }
      format.json { render json: @user, status: :created, location: @user }
    end
  end

  private
  def load_admin
    @user = current_user
  end

  def load_user
    @user = User.find(params[:id])
  end

  def verify_admin
    (current_user.nil?) ? redirect_to(user_url(current_user)) : (redirect_to(user_url(current_user), notice: 'Unauthorized')  unless current_user.admin?)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Raffle</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <%= image_tag 'Walk_Run_Header_2018.jpg', class:'banner' %>
    <% if user_signed_in? %>
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse-1" aria-expanded="false">
            <span class="glyphicon glyphicon-chevron-down"></span>
          </div>

          <div class="collapse navbar-collapse" id="collapse-1">
            <ul class="nav navbar-nav">
              <% if current_user.admin? %>
                <li class="<%= 'active' if current_page?(root_url) || current_page?(users_url) %>"><%= link_to "Home", users_url, class:"nav-link" %></li>
              <% end %>
              <li class='<%= "active" if current_page?(user_url(current_user)) %>'><%= link_to "Profile", user_url(current_user), class:"nav-link" %></li>
              <li class='<%= 'active' if current_page?('/users/edit')%>'><%= link_to "Settings", "/users/edit", class:"nav-link" %></li>
              <li class='<%= "active" if current_page?('/users/trash') %>'><%= link_to "Trash", "/users/trash", class:"nav-link" %></li>
              <li class='<%= "active" if current_page?('/users/bank_instructions') %>'><%= link_to "Bank Deposit Instructions", "/users/bank_instructions", class:"nav-link" %></li>
              <li><%= link_to "Logout", destroy_user_session_url, method: :delete, class:"nav-link" %></li>
            </ul>
            <% if flash[:notice] %>
              <div class="alert"><%= flash[:notice] %></div>
            <% end %>
          </div>
        </div>
      </nav>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/transactions/edit.html.erb
<div class="clean-row">
  <h2>Edit transaction details</h2>
</div>

<%= form_for(@transaction) do |f| %>
  <div class="row">
    <% if @transaction.errors.any? %>
      <h4 class="error-header"><%= pluralize(@transaction.errors.count, "error") %> occurred!</h4>

      <ul class="error-list">
        <% @transaction.errors.full_messages.each do |msg| %>
          <li class="error-msg"><%= msg %></li>
        <% end %>
      </ul>
    <% end %>

    <div class="row-field">
      <%= f.label :full_name, 'Full Name', class:"field-label" %>
    </div>

    <div class="row-field">
      <%= f.label :email, class:"field-label" %>
    </div>

    <div class="row-field">
      <%= f.label :ministry, class:"field-label" %>
    </div>

    <div class="row-field" id="half-width">
      <%= f.label :quantity, "Qty", class:"field-label" %>
    </div>

    <div class="row-field" id="half-width">
      <%= f.label :price, "Price", class:"field-label" %>
    </div>

    <div class="row-field">
      <%= f.label :payment_check, "Tickets paid for?", class:"field-label" %>
    </div>

    <div class="row-field">
      <%= f.label :deposit_check, "Money deposited?", class:"field-label" %>
    </div>

    <div class="row-field">
      <%= f.label :date_deposited, "Deposit Date", class:"field-label" %>
    </div>
  </div>

  <div class="row">
    <div class="row-field">
      <%= f.text_field :full_name, autofocus: true, class:"field-input" %>
    </div>

    <div class="row-field">
      <%= f.text_field :email, placeholder:"example@address.com", autofocus: true, class:"field-input" %>
    </div>

    <div class="row-field">
      <%= f.text_field :ministry, placeholder:"ex. MEDG", autofocus: true, class:"field-input" %>
    </div>

    <div class="row-field" id="entry">
      <%= f.number_field :quantity, placeholder:"2", autofocus: true, class:"field-input", id:"newEntry" %>
    </div>

    <div class="row-field" id="prices">
    </div>

    <div class="row-field" style="margin-top: 10px; text-align: center;">
      <%= f.check_box :payment_check, class:"field-input" %>
    </div>

    <div class="row-field" style="margin-top: 10px; margin-right: 70px; text-align: center;">
      <%= f.check_box :deposit_check, class:"field-input" %>
    </div>

    <div class="row-field">
      <%= f.date_field :date_deposited, class:"field-label", id:'no-arrows' %>
    </div>

    <div class="button-wrap">
      <%= f.submit "SAVE", class:"submit" %>

      <%= link_to "Back", :back, class:"cancel" %>
    </div>
  </div>
<% end %>

<%= javascript_include_tag 'price', 'data-turbolinks-track': 'reload' %>

app/views/users/bank_instructions.html.erb
<div class="left-align-wrap">
  <h2 class="left-text">Bank Deposit Instructions</h2>

  <p class="left-text">
    We request that all funds from the sale of the raffle tickets be directly deposited into the OPS Walk & Run TD Canada Trust bank account.
  </p>

  <p class="left-text">
    Follow the steps below:
  </p>

  <p class="left-text">
    1. Go to any TD Canada Trust branch in Ontario. Use the branch locator site to find a nearest location:
  </p>

  <p class="left-text" style="padding-left: 15px;">
    <b><%= link_to 'Branch Locator', 'https://www.tdcanadatrust.com/customer-service/contact-us/branch-locator/', target:'_blank' %></b>
  </p>

  <p class="left-text">
     2. Deposit the money collected into the OPS Walk & Run TD Canada Trust bank account. Provide the following information to the teller:
   </p>

  <ul class="left-text" style="padding-left: 30px; list-style: circle;">
    <li>Account #: 5228205</li>
    <li>Branch #: 1224</li>
    <li>Bank account: OPS Walk & Run for United Way</li>
  </ul>

  <p class="left-text">
    3. If you do not have a TD Canada Trust branch located near you, you can mail in a cheque and the deposit slip.
  </p>

  <div style="padding-left: 15px;">
    <p class="left-text">
      The cheque should be made payable to: <b>OPS Walk & Run for United Way</b>
    </p>

    <ul class="left-text">
      <li><b>Mailing Address:</b></li>
      <li>ATTN: Janet Lim</li>
      <li>56 Wellesley St West, 4th floor</li>
      <li>Toronto, ON M5S 2S3</li>
      <li>janet.lim@ontario.ca</li>
      <li>Corporate Services Division</li>
      <li>Ministry of Energy</li>
    </ul>
  </div>
</div>

app/views/users/index.html.erb
<div class="float">
  <div class="left-align-wrap" style="margin-bottom: 30px;">
    <h2><%= link_to '(Export All)', user_url(@user, format: 'csv') %></h2>
    <h2>Coordinator Progress</h2><br/>

    <% @users.each do |u| %>
      <p><%= link_to u.name, user_url(u), class:"link" %></p>
      <p><b><%= "#{u.transactions.where(payment_check: 1).count}" + "/" + "#{u.transactions.count}" %></b> transactions paid <b><%= "($#{'%.02f' % u.transactions.where(payment_check: 1, deposit_check: 0).sum(:price)})" %></b></p>
      <p><b><%= "#{u.transactions.where(deposit_check: 1).count}" + "/" + "#{u.transactions.count}" %></b> transactions deposited <b><%= "($#{'%.02f' % u.transactions.where(deposit_check: 1).sum(:price)})" %></b></p>
    <% end %>
  </div>
</div>

<div class="float">
  <div class="left-align-wrap" style="margin-bottom: 30px;">
    <h2>Purchased Ticket Info</h2><br/>

    <!-- As long as they've paid, display -->
    <% @transactions.each do |t| %>
      <p><b>Name:</b> <%= t.full_name %></p>
      <p><b>Ministry:</b> <%= t.ministry %></p>
      <p>
        <b>Ticket #'s:</b>
        <% t.tickets.each do |ticket| %>
          <%= "#{ticket.number}" + ", " %>
        <% end %>
      </p>
    <% end %>
  </div>
</div>

app/views/users/intro.html.erb
<div class="left-align-wrap">
  <h4 class='left-text'>Welcome to the OPS WalkRun Raffle Tracker</h4>

  <h4 class='left-text'>
    This application will allow you as a coordinator to more efficiently and accurately track raffle ticket purchases.
  </h4><br />

  <%= link_to 'Get Started', user_url(current_user), class:'submit', style:'text-align: center;' %>
</div>

app/views/users/show.html.erb
<% if current_user == @user %>
  <!-- <div class="clean-row">
    <h2 style="font-weight: normal;">
      The raffle is now closed and the winning ticket will be drawn on October
      31st at the Queen's Park event. Winners will be notified directly and posted
      on the website.
    </h2>
  </div> -->
  <div class="clean-row">
    <h2>Add transaction</h2>
  </div>

  <%= form_for([@user, @transaction]) do |f| %>
    <div class="row">
      <% if @transaction.errors.any? %>
        <h4 class="error-header"><%= pluralize(@transaction.errors.count, "error") %> occurred!</h4>

        <ul class="error-list">
          <% @transaction.errors.full_messages.each do |msg| %>
            <li class="error-msg"><%= msg %></li>
          <% end %>
        </ul>
      <% end %>

      <div class="row-field">
        <%= f.label :full_name, 'Full Name', class:"field-label" %>
      </div>
      <div class="row-field">
        <%= f.label :email, class:"field-label" %>
      </div>
      <div class="row-field">
        <%= f.label :ministry, class:"field-label" %>
      </div>
      <div class="row-field" id="half-width">
        <%= f.label :quantity, "Qty", class:"field-label" %>
      </div>
      <div class="row-field" id="half-width">
        <%= f.label :price, "Price", class:"field-label" %>
      </div>
      <div class="row-field">
        <%= f.label :payment_check, "Tickets paid for?", class:"field-label" %>
      </div>
      <div class="row-field">
        <%= f.label :deposit_check, "Money deposited?", class:"field-label" %>
      </div>
      <div class="row-field">
        <%= f.label :date_deposited, "Deposit Date", class:"field-label" %>
      </div>
    </div>

    <div class="row">
      <div class="row-field">
        <%= f.text_field :full_name, autofocus: true, class:"field-input" %>
      </div>
      <div class="row-field">
        <%= f.text_field :email, placeholder:"example@address.com", autofocus: true, class:"field-input" %>
      </div>
      <div class="row-field">
        <%= f.text_field :ministry, placeholder:"ex. MEDG", autofocus: true, class:"field-input" %>
      </div>
      <div class="row-field" id="entry">
        <%= f.number_field :quantity, placeholder:"2", autofocus: true, class:"field-input", id:"newEntry" %>
      </div>
      <div class="row-field" id="prices">
      </div>
      <div class="row-field" style="margin-top: 10px; text-align: center;">
        <%= f.check_box :payment_check, class:"field-input" %>
      </div>
      <div class="row-field" style="margin-top: 10px; margin-right: 70px; text-align: center;">
        <%= f.check_box :deposit_check, class:"field-input" %>
      </div>
      <div class="row-field">
        <%= f.date_field :date_deposited, class:"field-label", id:'no-arrows' %>
      </div>

      <%= f.hidden_field :user_id, value: @user.id %>

      <div class="button-wrap">
        <%= f.submit "SAVE", class:"submit" %>
      </div>
    </div>
  <% end %>
<% end %>

<div class="clean-row">
  <% if current_user != @user %>
    <h2 class="left-title"><%= @user.name.capitalize %>'s Current transactions</h2>
  <% else %>
    <h2 class="left-title">Current transactions</h2>
  <% end %>
</div>

<% @transactions.each_with_index do |t, i| %>
  <div class="row">
    <h4 class="column" id="italic"><%= i + 1 %>)</h4>
    <p class="column"><b>Full Name:</b> <%= t.full_name %></p>
    <p class="column"><b>Email:</b> <%= t.email %></p>
    <p class="column"><b>Ministry:</b> <%= t.ministry %></p>
    <p class="column"><b>Quantity:</b> <%= t.quantity %></p>
    <p class="column"><b>Price:</b> <%= "$#{'%.02f' % t.price}" %></p>
    <p class="column" id="mixed-content">
      <b class="precise-position">Paid?:</b>
      <% if t.payment_check != 1 %>
        <span class="glyphicon glyphicon-remove" style="color: #b71c1c;"></span>
      <% else %>
        <span class="glyphicon glyphicon-ok" style="color: #F6AE1C;"></span>
      <% end %>
    </p>
    <p class="column" id="mixed-content">
      <b class="precise-position">Deposited?:</b>
      <% if t.deposit_check != 1 %>
        <span class="glyphicon glyphicon-remove" style="color: #b71c1c;"></span>
      <% else %>
        <span class="glyphicon glyphicon-ok" style="color: #F6AE1C;"></span>
      <% end %>
    </p>
    <p class="column" style="padding-bottom: 10px;">
      <b>Deposit Date:</b> <%= t.date_deposited %>
    </p>
    <p class="column">
      <b>Ticket #(s):</b>
      <% t.tickets.each do |ticket| %>
        <%= ticket.number %>/
      <% end %>
    </p>
    <% if t.payment_check == 1 && t.sent_confirmation != 1 %>
      <div class="column">
        <%= link_to "Send tickets to #{t.full_name.titleize}", controller: 'users', action: 'send_payment_confirmation', id: t.id %>
      </div>
    <% elsif t.sent_confirmation == 1 %>
      <div class="column" style="color: green; font-weight: bold;">
        <%= "Ticket confirmation email sent #{t.full_name.titleize}, please remind them to check their junkbox if email isn't found." %>
      </div>
      <div class="column">
        <%= link_to "Resend tickets", controller: 'users', action: 'send_payment_confirmation', id: t.id %>
      </div>
    <% end %>
    <div class="column">
      <%= link_to edit_transaction_url(t), class:'row-link' do %>
        <span class='glyphicon glyphicon-edit'></span>
      <% end %>
    </div>
    <div class="column" id="end-column">
      <%= link_to user_transaction_url(user_id: current_user.id, id: t.id), method: :delete, data: { confirm: "Delete transaction data?" }, class:'row-link' do %>
        <span class="glyphicon glyphicon-trash" id="red"></span>
      <% end %>
    </div>
  </div>
<% end %>

<div class="third">
  <p class='sub-header'>Total Cash Owed</p>
  <%= "$#{'%.02f' % @transactions.where.not(payment_check: 1, deposit_check: 1).sum(:price)}" %>
</div>
<div class="third">
  <p class='sub-header'>Total Cash On Hand</p>
  <%= "$#{'%.02f' % @transactions.where(payment_check: 1, deposit_check: 0).sum(:price)}" %>
</div>
<div class="third">
  <p class='sub-header'>Total Cash Deposited</p>
  <%= "$#{'%.02f' % @transactions.where(deposit_check: 1).sum(:price)}" %>
</div>

<%= javascript_include_tag 'price', 'data-turbolinks-track': 'reload' %>

app/views/users/trash.html.erb
<% @transactions.each_with_index do |t, i| %>
  <div class="row">
    <h4 class="column" id="italic"><%= i + 1 %>)</h4>
    <p class="column"><b>Full Name:</b> <%= t.full_name %></p>
    <p class="column"><b>Email:</b> <%= t.email %></p>
    <p class="column"><b>Ministry:</b> <%= t.ministry %></p>
    <p class="column"><b>Quantity:</b> <%= t.quantity %></p>
    <p class="column"><b>Price:</b> <%= "$#{'%.02f' % t.price}" %></p>
    <p class="column" id="mixed-content">
      <b class="precise-position">Paid?:</b>
      <% if t.payment_check != 1 %>
        <span class="glyphicon glyphicon-remove" style="color: #b71c1c;"></span>
      <% else %>
        <span class="glyphicon glyphicon-ok" style="color: #F6AE1C;"></span>
      <% end %>
    </p>
    <p class="column" id="mixed-content">
      <b class="precise-position">Deposited?:</b>
      <% if t.deposit_check != 1 %>
        <span class="glyphicon glyphicon-remove" style="color: #b71c1c;"></span>
      <% else %>
        <span class="glyphicon glyphicon-ok" style="color: #F6AE1C;"></span>
      <% end %>
    </p>
    <p class="column" style="padding-bottom: 10px;">
      <b>Deposit Date:</b> <%= t.date_deposited %>
    </p>
    <p class="column">
      <b>Ticket #(s):</b>
      <% t.tickets.each do |ticket| %>
        <%= ticket.number %>/
      <% end %>
    </p>
    <div class="column">
      <%= link_to 'Restore Transaction Data', controller: 'transactions', action: 'restore_data', id: t.id %>
    </div>
  </div>
<% end %>